In [16]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Data/eeg_features.csv")

In [48]:
transactions= pd.DataFrame()

for zone in ["F4", "C4", "E2"]:
    for wave in ["alpha", "delta", "theta", "gamma", "beta"]:
        col_name = f"{zone}_bp_{wave}"
        transactions[col_name] = df[col_name] > df[col_name].median()

In [ ]:
col_name = "F4_bp_alpha"
 
np.mean(df[col_name] > df[col_name].median())

np.float64(0.5)

In [50]:
transactions

,F4_bp_alpha,F4_bp_delta,F4_bp_theta,F4_bp_gamma,F4_bp_beta,C4_bp_alpha,C4_bp_delta,C4_bp_theta,C4_bp_gamma,C4_bp_beta,E2_bp_alpha,E2_bp_delta,E2_bp_theta,E2_bp_gamma,E2_bp_beta
0,True,False,True,True,True,True,False,True,False,True,False,True,True,True,True
1,False,True,True,False,False,True,True,True,False,False,True,True,True,True,False
2,False,True,True,False,False,False,True,False,False,False,False,True,True,True,True
3,True,True,True,False,True,True,True,True,False,True,True,True,True,True,True
4,True,True,True,False,False,True,True,True,False,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False
90,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False
91,False,True,True,True,True,False,True,True,True,True,False,False,True,True,False
92,False,True,True,True,True,True,False,True,True,False,False,False,False,False,False
93,False,True,False,True,True,False,True,False,True,False,False,True,False,True,False

In [57]:
from mlxtend.frequent_patterns import apriori, association_rules
frequent_itemsets = apriori(transactions, 
                            min_support=0.2, 
                            use_colnames=True)

rules = association_rules(frequent_itemsets, 
                          metric="confidence", 
                          min_threshold=0.2)

In [58]:
rules.sort_values(by = "support", ascending=False).head(15)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
129,(E2_bp_alpha),(C4_bp_alpha),0.5,0.5,0.372340,0.744681,1.489362,1.0,0.122340,1.958333,0.657143,0.593220,0.489362,0.744681
128,(C4_bp_alpha),(E2_bp_alpha),0.5,0.5,0.372340,0.744681,1.489362,1.0,0.122340,1.958333,0.657143,0.593220,0.489362,0.744681
9,(C4_bp_alpha),(F4_bp_alpha),0.5,0.5,0.361702,0.723404,1.446809,1.0,0.111702,1.807692,0.617647,0.566667,0.446809,0.723404
8,(F4_bp_alpha),(C4_bp_alpha),0.5,0.5,0.361702,0.723404,1.446809,1.0,0.111702,1.807692,0.617647,0.566667,0.446809,0.723404
87,(C4_bp_gamma),(F4_bp_gamma),0.5,0.5,0.361702,0.723404,1.446809,1.0,0.111702,1.807692,0.617647,0.566667,0.446809,0.723404
86,(F4_bp_gamma),(C4_bp_gamma),0.5,0.5,0.361702,0.723404,1.446809,1.0,0.111702,1.807692,0.617647,0.566667,0.446809,0.723404
143,(C4_bp_beta),(C4_bp_delta),0.5,0.5,0.351064,0.702128,1.404255,1.0,0.101064,1.678571,0.575758,0.540984,0.404255,0.702128
142,(C4_bp_delta),(C4_bp_beta),0.5,0.5,0.351064,0.702128,1.404255,1.0,0.101064,1.678571,0.575758,0.540984,0.404255,0.702128
62,(C4_bp_theta),(F4_bp_theta),0.5,0.5,0.340426,0.680851,1.361702,1.0,0.090426,1.566667,0.531250,0.516129,0.361702,0.680851
63,(F4_bp_theta),(C4_bp_theta),0.5,0.5,0.340426,0.680851,1.361702,1.0,0.090426,1.566667,0.531250,0.516129,0.361702,0.680851
61,(F4_bp_theta),(C4_bp_delta),0.5,0.5,0.340426,0.680851,1.361702,1.0,0.090426,1.566667,0.531250,0.516129,0.361702,0.680851
60,(C4_bp_delta),(F4_bp_theta),0.5,0.5,0.340426,0.680851,1.361702,1.0,0.090426,1.566667,0.531250,0.516129,0.361702,0.680851
139,(C4_bp_theta),(C4_bp_delta),0.5,0.5,0.340426,0.680851,1.361702,1.0,0.090426,1.566667,0.531250,0.516129,0.361702,0.680851
138,(C4_bp_delta),(C4_bp_theta),0.5,0.5,0.340426,0.680851,1.361702,1.0,0.090426,1.566667,0.531250,0.516129,0.361702,0.680851
188,(C4_bp_beta),(E2_bp_beta),0.5,0.5,0.340426,0.680851,1.361702,1.0,0.090426,1.566667,0.531250,0.516129,0.361702,0.680851

In [60]:
rules.sort_values(by = "confidence", ascending=False).head(15)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
897,"(E2_bp_alpha, C4_bp_beta, E2_bp_beta)",(C4_bp_alpha),0.202128,0.5,0.202128,1.000000,2.000000,1.0,0.101064,inf,0.626667,0.404255,1.000000,0.702128
235,"(F4_bp_alpha, C4_bp_beta)",(C4_bp_alpha),0.234043,0.5,0.223404,0.954545,1.909091,1.0,0.106383,11.00,0.621693,0.437500,0.909091,0.700677
824,"(C4_bp_delta, F4_bp_theta, C4_bp_beta)",(C4_bp_theta),0.234043,0.5,0.223404,0.954545,1.909091,1.0,0.106383,11.00,0.621693,0.437500,0.909091,0.700677
812,"(F4_bp_alpha, E2_bp_alpha, E2_bp_beta)",(C4_bp_alpha),0.223404,0.5,0.212766,0.952381,1.904762,1.0,0.101064,10.50,0.611644,0.416667,0.904762,0.688956
852,"(F4_bp_gamma, C4_bp_delta, C4_bp_beta)",(C4_bp_gamma),0.212766,0.5,0.202128,0.950000,1.900000,1.0,0.095745,10.00,0.601707,0.395833,0.900000,0.677128
516,"(F4_bp_gamma, C4_bp_beta)",(C4_bp_gamma),0.297872,0.5,0.276596,0.928571,1.857143,1.0,0.127660,7.00,0.657343,0.530612,0.857143,0.740881
662,"(E2_bp_alpha, C4_bp_beta)",(C4_bp_alpha),0.287234,0.5,0.265957,0.925926,1.851852,1.0,0.122340,6.75,0.645373,0.510204,0.851852,0.728920
625,"(C4_bp_alpha, C4_bp_delta)",(E2_bp_alpha),0.244681,0.5,0.223404,0.913043,1.826087,1.0,0.101064,5.75,0.598927,0.428571,0.826087,0.679926
763,"(C4_bp_theta, E2_bp_beta)",(C4_bp_beta),0.244681,0.5,0.223404,0.913043,1.826087,1.0,0.101064,5.75,0.598927,0.428571,0.826087,0.679926
883,"(C4_bp_beta, C4_bp_gamma, E2_bp_beta)",(F4_bp_gamma),0.234043,0.5,0.212766,0.909091,1.818182,1.0,0.095745,5.50,0.587500,0.408163,0.818182,0.667311
882,"(F4_bp_gamma, C4_bp_gamma, E2_bp_beta)",(C4_bp_beta),0.234043,0.5,0.212766,0.909091,1.818182,1.0,0.095745,5.50,0.587500,0.408163,0.818182,0.667311
881,"(F4_bp_gamma, C4_bp_beta, E2_bp_beta)",(C4_bp_gamma),0.234043,0.5,0.212766,0.909091,1.818182,1.0,0.095745,5.50,0.587500,0.408163,0.818182,0.667311
838,"(F4_bp_beta, F4_bp_gamma, C4_bp_beta)",(C4_bp_gamma),0.234043,0.5,0.212766,0.909091,1.818182,1.0,0.095745,5.50,0.587500,0.408163,0.818182,0.667311
839,"(F4_bp_beta, F4_bp_gamma, C4_bp_gamma)",(C4_bp_beta),0.234043,0.5,0.212766,0.909091,1.818182,1.0,0.095745,5.50,0.587500,0.408163,0.818182,0.667311
866,"(F4_bp_gamma, C4_bp_theta, C4_bp_beta)",(C4_bp_gamma),0.223404,0.5,0.202128,0.904762,1.809524,1.0,0.090426,5.25,0.576063,0.387755,0.809524,0.654509

In [61]:
transactions.to_csv("../Data/transactions.csv")